### ISSUE TITLE
External coil test

### ISSUE THREAD

**Issue by qqmajikpp** [zacharyweiss/magspoof_flipper#5]
Is the external coil option confirmed to work? I built a coil and I can't seem to get it to work. 
![20230209_184509](https://user-images.githubusercontent.com/84942886/217966854-af27d953-fb63-46f8-a3e9-9402371d4bfa.jpg)
![20230209_183048](https://user-images.githubusercontent.com/84942886/217966876-c977acd0-8f24-4160-bafd-b85baedf9157.jpg)
![20230209_183859](https://user-images.githubusercontent.com/84942886/217966898-1f8ff2f1-3702-4584-9c52-d1e53d6ac664.jpg)

**Comment by qqmajikpp** [comment]
![20230210_081206](https://user-images.githubusercontent.com/84942886/218101273-74c23c4c-5841-4581-bf17-d342ce9d0ee6.jpg)

https://user-images.githubusercontent.com/84942886/218101299-44a0ecd0-e555-411f-9669-f34fe3127f71.mp4

I redid everything. New chips, new coil. Same issue

**Comment by qqmajikpp** [comment]
So I got the coil to spoof twice.  Not sure what I did or what it stopped working

**Comment by arha** [comment]
You _are_ emulating a track with data, and not just an empty one like above, right?

**Comment by gornstein** [comment]
Has driving the external TX antenna using the flippers 5v supply been tested? Id recommend driving pin 8 (Vcc2) of the L293D with a 9v or something other than the flipper (between 4.5-36v). Leave pin ~~18~~ 16 (Vcc1) on the flippers 5v GPIO output, that's for the IC logic.
Edit: Pin 16 is Vcc1 for L293D, not pin 18

**Comment by arha** [comment]
> Has driving the external TX antenna using the flippers 5v supply been tested? 

Directly? I couldn't get the GPIO 1 pin past 20Hz, so that's DOA. Note that 1 is VCC and 18 is gnd.

> Id recommend driving pin 8 (Vcc2) of the L293D with a 9v or something other than the flipper (between 4.5-36v). Leave pin 18 (Vcc1) on the flippers 5v GPIO output, that's for the IC logic.

I'm personally not too worried, since the original magspoof and its countless clones drove the L293 with 3.7v straight off a cell and although it shouldn't, there are numerous reports that the driver works just fine anyway. To me, this is on the border between having enough external hardware that the F0 stops making sense - why make it an external module for it, and have to carry it around, when you can stick an MCU in there along all that extra hardware, and not need the F0 at all?

What you can do - and it should be quite easy is to pull those 5V@20Hz off GPIO1 through a Cockcroft multiplier into higher voltages. But you'll want some fat caps, and at that point, you're better off with an external battery or a DC-DC converter and another fat coil.

edit: but I am making a note to try higher voltages on the H bridge. It might give it some amazing range.

**Comment by zacharyweiss** [comment]
I have indeed tested the external TX using just the Flipper's 5V and an L293D; confirmed working against an MSR90. That said, there's been a number of changes to the code since then, so I'll try to reconfirm it's working on current versions this weekend.

**Comment by arha** [comment]
> I have indeed tested the external TX using just the Flipper's 5V and an L293D; confirmed working against an MSR90. That said, there's been a number of changes to the code since then, so I'll try to reconfirm it's working on current versions this weekend.

Last coil test was on [fd112e3a](https://github.com/zacharyweiss/magspoof_flipper/commit/fd112e3a34155b56bb403b719739c825a71342b0), I think?
